name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.6
        with:
          # Source folder to check formatting
          source: './src'
          style: mozilla
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jwes/nginx-module-build-action@v0.1.0
        with:
          nginx-version: "release-1.18.0"
          additional-packages: "libpq-dev"
